import { PrismaClient, ExerciseCategory, TrackField } from '@prisma/client';

const prisma = new PrismaClient();

// ============================================================================
// EXERCISE DATA — this array is the source of truth. Edit docs/exercise-list.md
// first, then mirror the change here, then run this script against whichever
// environment needs it. Safe to rerun anytime, anywhere — matches by name
// (case-insensitive) and updates in place rather than duplicating.
// ============================================================================
const EXERCISES: {
  name: string;
  category: ExerciseCategory;
  description?: string;
  link?: string;
  trackedFields?: TrackField[]; // omit to use the category default below
}[] = [
  // CHEST
  { name: 'Bench Press', category: 'CHEST', description: 'Barbell bench press performed flat, targeting the pectorals, anterior deltoids, and triceps. Set up with shoulder-blade retraction and a slight arch; lower the bar to mid-chest with control before pressing. A foundational horizontal push movement.', link: 'https://youtube.com/shorts/hWbUlkb5Ms4?si=xJoTLrmDngjr4bSM' },
  { name: 'Close-Grip Bench Press', category: 'CHEST', description: 'Barbell bench press with a narrower grip (roughly shoulder-width), shifting emphasis toward the triceps while still engaging the chest and anterior deltoid. Keep elbows closer to the body than a standard bench press to protect the wrists and maximize tricep recruitment.', link: 'https://youtube.com/shorts/xXd7sddHGa0?si=ZeIv2XSPvJc7zgXm' },
  { name: 'Incline Dumbbell Chest Press', category: 'CHEST', description: 'Dumbbell press on a bench set to approximately 30 degrees, with palms facing each other. The incline angle increases upper chest and anterior deltoid involvement; neutral grip reduces shoulder stress compared to a pronated grip.', link: 'https://youtube.com/shorts/8fXfwG4ftaQ?si=cS6QKIOp4koFbEN5' },
  { name: 'Cable Chest Press', category: 'CHEST', description: 'Unilateral or bilateral horizontal press using a cable machine, typically set at chest height. Provides constant tension throughout the range of motion, making it effective for chest hypertrophy with less joint loading than a barbell.', link: 'https://youtube.com/shorts/NXpRKhXg2P8?si=yHf4vP5fDLvhuZnM' },
  { name: 'Scapular Push Up', category: 'CHEST', description: 'Bodyweight movement performed from a push-up or plank position, moving only through the shoulder blades — elbows stay locked while the scapula protracts and retracts. Isolates the serratus anterior and lower trapezius; commonly used as a warm-up or corrective drill to build scapular control and shoulder stability, especially useful for overhead athletes or as injury-prevention work.', link: 'https://youtube.com/shorts/emB58J1SyXA?si=zyAWd_B5KcA4gcrA' },
  { name: 'Dips', category: 'CHEST', description: 'Bodyweight or weighted dip performed on parallel bars, lowering the body until the upper arms are roughly parallel to the floor before pressing back up. Leaning the torso forward shifts emphasis toward the chest and front deltoids; staying upright targets the triceps more directly.', link: 'https://youtube.com/shorts/SXBksC78v8M?si=TEwSt5kZ8mC5s8As' },
  { name: 'Push-Up', category: 'CHEST', description: 'Standard bodyweight push-up from a plank position, hands roughly shoulder-width. Lower the chest toward the floor keeping the body in a straight line, then press back up. Core and glutes braced throughout to prevent the hips sagging or piking — the standard test-format pressing movement.', link: 'https://youtube.com/shorts/4Bc1tPaYkOo?si=SfIznkS_EBSC0ibW' },

  // BACK
  { name: 'Deadlift', category: 'BACK', description: 'Conventional barbell deadlift from the floor, training the entire posterior chain — erectors, glutes, hamstrings, and upper back. Brace hard, maintain a neutral spine, and drive the floor away rather than pulling the bar up.' },
  { name: 'Sumo Deadlift', category: 'BACK', description: 'Deadlift variation with a wide stance and toes pointed outward, reducing the range of motion and shifting some load from the lower back to the hips and inner thighs. Technically demanding hip-hinge pattern; well-suited for individuals with longer torsos or hip anatomy that limits conventional pulling.' },
  { name: 'Zercher Deadlift', category: 'BACK', description: 'Deadlift with the bar held in the crook of the elbows rather than the hands, creating a more upright torso angle and high core demand. Trains the posterior chain similarly to a conventional deadlift but with greater anterior core and upper back involvement.' },
  { name: 'Romanian Deadlift', category: 'BACK', description: 'Hip-hinge movement starting from standing, lowering the bar along the legs while maintaining a slight knee bend and neutral spine. Primarily targets the hamstrings and glutes through a loaded stretch; does not touch the floor between reps.' },
  { name: 'B-Stand RDL', category: 'BACK', description: 'Single-leg Romanian deadlift where the non-working foot\'s toe rests lightly on the ground behind and to the side for balance ("kickstand" stance), without bearing load. Bridges bilateral RDL and full single-leg RDL — trains each leg\'s hamstring/glute unilaterally and exposes side-to-side imbalances, with less balance demand than a freestanding single-leg RDL.' },
  { name: 'Single-Leg RDL', category: 'BACK', description: 'Freestanding single-leg Romanian deadlift — the non-working leg lifts and extends behind the body for counterbalance while the working leg hinges to lower the weight. Higher balance and hip-stability demand than the B-Stand RDL; effective for hamstring/glute strength and unilateral hip control.' },
  { name: 'Lat Pulldown', category: 'BACK', description: 'Cable machine exercise pulling a wide or neutral-grip bar down to the upper chest, targeting the latissimus dorsi and biceps. Focus on driving the elbows down and back rather than pulling with the hands to maximize lat engagement.' },
  { name: 'Seated Cable Row', category: 'BACK', description: 'Horizontal pull on a cable machine with a neutral or pronated grip, seated with knees slightly bent. Targets the mid-back (rhomboids, mid-traps, and lats) and biceps. Keep the torso upright and avoid using momentum.' },
  { name: 'Low Cable Row', category: 'BACK', description: 'Horizontal cable row with a low pulley attachment, performed with a straight back and minimal torso movement. Distinguished from a seated cable row by its setup angle and handle position, emphasizing a slightly different pull angle on the lower lats and mid-back.' },
  { name: 'Single-Arm Dumbbell Row', category: 'BACK', description: 'Unilateral row with one knee and hand braced on a bench, pulling a dumbbell from a hanging position to the hip. Allows a large range of motion and heavy loading; targets the lats, rhomboids, and rear deltoid with reduced compensation from the opposite side.' },
  { name: 'Back Extension', category: 'BACK', description: 'Hyperextension movement performed on a back extension bench or GHD, training the erector spinae, glutes, and hamstrings. Can be loaded with a plate or kept bodyweight; hinge at the hips rather than rounding the spine.' },
  { name: 'Nordic Curl', category: 'BACK', description: 'Eccentric-dominant hamstring exercise where the feet are anchored and the body lowers toward the floor under control. One of the most effective exercises for hamstring injury prevention; extremely demanding — beginners typically need bands for assistance.' },
  { name: 'Chin-Up', category: 'BACK', description: 'Bodyweight pull-up performed with an underhand (supinated) grip, emphasizing the lats and biceps more than a standard overhand pull-up. Pull until the chin clears the bar; add weight via a dip belt once bodyweight reps are no longer challenging.' },
  { name: 'Pull-Up', category: 'BACK', description: 'Bodyweight or weighted pull-up performed with an overhand (pronated) grip, the standard competition/test-format vertical pull. Pull until the chin clears the bar; add weight via a dip belt once bodyweight reps are no longer challenging. More back/lat-dominant and less bicep-driven than the underhand Chin-Up.' },
  { name: 'Shrugs', category: 'BACK', description: 'Barbell or dumbbell shrug lifting the shoulders straight up toward the ears to target the upper trapezius. Avoid rolling the shoulders — a straight vertical path keeps tension on the traps and reduces shoulder-joint strain.' },
  { name: 'Straight-Arm Cable Pulldown', category: 'BACK', description: 'Cable exercise pulling a high-anchored bar or rope straight down toward the thighs with the arms kept mostly locked out, isolating the lats with minimal bicep involvement. A useful complement to bent-arm pulling work (rows, pulldowns) when more direct lat isolation is wanted; keep a slight elbow bend and avoid using the torso to swing the weight down.' },
  { name: 'Scapular Pull-Up', category: 'BACK', description: 'Hanging from a bar with arms fully extended, pull only through the shoulder blades — elbows stay locked — driving the shoulder blades down and together, then release back to a dead hang. Mirrors the Scapular Push-Up as a corrective/prep drill; builds the scapular control that strict chin-ups depend on before adding elbow-bend pulling volume.' },
  { name: 'Band-Assisted Chin-Up', category: 'BACK', description: 'Chin-up assisted by a resistance band anchored a few meters below the bar (looped around a rack mount, not around the bar itself) and under a knee or foot, offsetting part of your bodyweight to allow more/cleaner strict reps than bodyweight alone. Standard progression tool toward unassisted chin-ups — reduce band tension as strength improves.' },
  { name: 'Inverted Row', category: 'BACK', description: 'Bodyweight horizontal row performed hanging under a bar or in a rack, pulling the chest toward it while the body stays rigid from heels to head. Regressed by raising the bar (more upright body) or progressed by lowering it (closer to horizontal) — a bodyweight scaling tool for the same pulling pattern as the cable/dumbbell rows above.' },
  { name: 'Floating RDL', category: 'BACK', description: 'Romanian deadlift performed without resetting the bar on the floor between reps — tension stays on the hamstrings continuously from the top of one rep into the next. Same hip-hinge mechanics as the standard RDL, but the removed "reset" makes it harder to lose position rep to rep.' },
  { name: 'Good Morning', category: 'BACK', description: 'Barbell held across the upper back as in a squat, hinging forward at the hips with a soft knee bend until the torso is roughly parallel to the floor, then returning upright. Trains the posterior chain (erectors, glutes, hamstrings) similarly to an RDL but with the load on the back rather than in the hands — technically demanding, start light.' },
  { name: 'Rack Pull', category: 'BACK', description: 'Partial-range deadlift starting from pins set just below or at knee height, removing the floor-to-knee portion of the pull. Allows heavier loading than a full deadlift with less lower-back demand, useful for building top-end pulling strength and lockout.' },
  { name: 'Rope Climb', category: 'BACK', description: 'Climbing a suspended rope hand-over-hand using a leg-lock or foot-hook technique to unweight the arms between pulls. Heavy grip, lat, and bicep demand; scale with a shorter rope, an assisted descent, or a legless variation once basic climbs are solid.' },
  { name: 'Trap Bar Deadlift (High Handles)', category: 'BACK', description: "Deadlift using a trap/hex bar's higher handle position, shortening the pull range and keeping the torso more upright than a barbell deadlift. A gentler entry point for the trap bar pattern — good for beginners or as a lighter-load, higher-volume variation." },
  { name: 'Trap Bar Deadlift (Low Handles)', category: 'BACK', description: "Deadlift using a trap/hex bar's lower handle position, closer in range of motion and torso angle to a conventional barbell deadlift than the high-handle version. More posterior-chain demand than the high-handle variant; use once the high-handle pattern is solid." },

  // LEGS
  { name: 'Barbell Squat', category: 'LEGS', description: 'Hip-width barbell back squat, the cornerstone lower-body strength movement targeting quads, glutes, and adductors. Brace the core, sit into the hips, and drive the knees out over the toes; depth should reach at least parallel.', link: 'https://youtube.com/shorts/PPmvh7gBTi0?si=Kl_KQUTKh-SnfeQt' },
  { name: 'Front Squat', category: 'LEGS', description: 'Barbell squat with the bar racked on the front deltoids, requiring a more upright torso than a back squat. Demands significant thoracic mobility and wrist flexibility; heavily loads the quads and places less shear on the lower back.' },
  { name: 'Goblet Squat', category: 'LEGS', description: 'Squat variation holding a kettlebell or dumbbell at chest height, naturally promoting an upright torso and good squat mechanics. Excellent for building a squat pattern in beginners or as a warm-up/accessory for experienced lifters.' },
  { name: 'Zercher Squat', category: 'LEGS', description: 'Squat with the barbell held in the crook of the elbows, forcing an upright posture and high core tension throughout. Builds significant anterior core and upper back strength alongside quad and glute development; easier on the wrists than a front squat.' },
  { name: 'Bulgarian Split Squat', category: 'LEGS', description: "Rear-foot elevated split squat targeting the front leg's quad and glute. Balance demands are high; load with dumbbells or a barbell. Rear foot elevation increases the range of motion and hip flexor stretch on the back leg." },
  { name: 'Hip Thrust', category: 'LEGS', description: 'Loaded glute bridge with the upper back on a bench and a barbell across the hips. One of the most effective exercises for glute development through hip extension. Drive through the heels and squeeze hard at the top; keep the chin tucked.' },
  { name: 'Leg Extension', category: 'LEGS', description: 'Isolation exercise for the quadriceps performed on a machine, extending the knee against resistance. Useful for quad hypertrophy and rehab contexts; avoid excessive load if there is existing knee discomfort.' },
  { name: 'Lying Leg Curl', category: 'LEGS', description: 'Hamstring isolation exercise performed prone on a machine, curling the heels toward the glutes. Trains the hamstrings through knee flexion; complement with hip-dominant exercises (RDL, Nordic curl) for full hamstring development.' },
  { name: 'Standing Calf Raise', category: 'LEGS', description: 'Isolation movement for the gastrocnemius and soleus, pressing through the balls of the feet to full plantarflexion. Train through a full range of motion including a deep stretch at the bottom; can be performed on a machine, step, or with a barbell.' },
  { name: 'Dumbbell Step-Up', category: 'LEGS', description: 'Unilateral lower-body exercise stepping onto a box or bench with dumbbells, targeting the quad and glute of the working leg. Step height determines difficulty and hip angle; avoid pushing off the trailing foot.' },
  { name: 'Cable Hip Abduction', category: 'LEGS', description: 'Standing hip abduction using a low cable attachment, isolating the glutes (primarily gluteus medius) and hip abductors. Keep the torso upright and control the return to avoid compensating with the lower back.', link: 'https://youtu.be/wDvzvj6AeL4?si=3koi97rtCsfLpOrL' },
  { name: 'Banded Lateral Walk', category: 'LEGS', description: 'Lateral stepping with a resistance band around the ankles or knees, activating the glute medius and hip abductors. Commonly used in warm-ups and rehab; maintain a slight squat position and level hips throughout.' },
  { name: 'Banded Clamshells', category: 'LEGS', description: 'Side-lying hip external rotation with a resistance band above the knees. Isolates the glute medius and external rotators; commonly used in warm-ups and injury prevention programs for the hip and knee.' },
  { name: 'Leg Press', category: 'LEGS', description: 'Machine-based compound leg exercise pressing a weighted platform away from the body while seated in a reclined position. Allows heavy loading of the quads and glutes with less spinal loading and balance demand than a free-weight squat.' },
  { name: 'Seated Leg Curl', category: 'LEGS', description: 'Hamstring isolation exercise performed seated on a machine, curling the lower legs down and back against resistance. The seated angle changes hip position relative to a lying leg curl, shifting the stretch and loading slightly higher in the hamstring.' },
  { name: 'Sled Push/Pull', category: 'LEGS', description: 'Loaded sled driven forward (push) or dragged backward (pull) across a set distance, combining leg drive with a significant conditioning demand. Low eccentric loading makes it a joint-friendly way to build leg power and work capacity; distance and added weight are both easy to progress.', trackedFields: ['DISTANCE', 'WEIGHT'] },
  { name: 'Terminal Knee Extension', category: 'LEGS', description: 'Banded knee extension performed through only the final few degrees of extension, using a resistance band anchored behind the knee. Isolates the VMO (vastus medialis oblique); a staple rehab exercise after knee injury or surgery since it avoids loading the joint through a full range of motion.' },
  { name: 'Seated Calf Raise', category: 'LEGS', description: 'Isolation movement for the soleus performed seated with the knee bent, pressing through the balls of the feet against a pad or machine. The bent-knee position takes the gastrocnemius largely out of play compared to a standing calf raise, shifting emphasis to the soleus — gentler on the knee joint too.' },
  { name: 'Single-Leg Glute Bridge', category: 'LEGS', description: "Unilateral bodyweight glute bridge — one foot planted, hips driven up while the other leg stays extended or lifted. Bodyweight-only counterpart to the Hip Thrust, useful when heavy spinal or hip loading isn't appropriate; also exposes left-right glute imbalances." },
  { name: 'Side-Lying Hip Abduction', category: 'LEGS', description: 'Side-lying leg raise lifting the top leg straight up against gravity or a band, isolating the hip abductors and gluteus medius. Low-load, joint-friendly way to build hip stability — commonly used in rehab and warm-ups.' },
  { name: 'Copenhagen Adductor', category: 'LEGS', description: "Side plank variation with the top leg supported on a bench, training the hip adductors through an isometric or dynamic hold. The modified/regressed version supports the top leg closer to the knee rather than the ankle, shortening the lever arm for a knee-friendlier entry point.", link: 'https://youtu.be/HOmsC6HEiFU?si=KGQ5H39hBG7wN1Cc' },
  { name: 'Single-Leg Bridge with Stability Ball and Abduction', category: 'LEGS', description: 'Lie on your back, one leg extended and resting on a stability ball, the other held straight in the air. Lift the hips until the body forms a straight line, then sweep the raised leg out to the side and back before lowering. Combines a single-leg glute bridge with a hip-abduction component; useful for hip and knee stability work.', link: 'https://exorlive.com/video/?culture=sv-SE&hidesmb=true&ex=8307' },
  { name: 'Single-Leg Three-Point Balance Reach', category: 'LEGS', description: 'Standing on one leg, reach the free leg out to three points forming a triangle — straight ahead, diagonally back to one side, then diagonally back to the other — returning to center between each without the reaching leg taking any weight. A stability/proprioception drill for the standing knee and hip; use a chair for balance support if needed.', link: 'https://exorlive.com/video/?culture=sv-SE&hidesmb=true&ex=14656' },
  { name: 'Single-Leg Jump Landing', category: 'LEGS', description: 'Start with feet shoulder-width apart, jump straight up, and land under control on one leg. Trains landing mechanics and knee stability under impact — focus on a soft, controlled landing rather than jump height.', link: 'https://exorlive.com/video/?culture=sv-SE&hidesmb=true&ex=14552' },
  { name: 'Box Jump (Low Box)', category: 'LEGS', description: 'Take a small countermovement — bend the knees and swing the arms — then jump onto a low box, landing softly with bent knees. Builds explosive lower-body power; landing quality matters more than box height.', link: 'https://exorlive.com/video/?culture=sv-SE&hidesmb=true&ex=12730' },
  { name: 'Lunge to Step-Up with Knee Raise', category: 'LEGS', description: 'Stand one stride behind a step. Place one foot on the step, lower into a deep lunge, then drive up through that leg onto the step in one controlled motion, finishing by lifting the opposite knee to stand tall on one leg. Return to the start and repeat — combines a lunge, step-up, and single-leg balance finish in one movement.', link: 'https://exorlive.com/video/?culture=sv-SE&hidesmb=true&ex=12159' },
  { name: 'Curtsy Dumbbell Lunge', category: 'LEGS', description: 'Lunge stepping one leg diagonally back and across behind the other, like a curtsy, lowering until both knees bend to roughly 90 degrees. Adds a glute medius/adductor demand on top of the standard lunge\'s quad/glute work through the diagonal step path.' },
  { name: 'Hack Squat (Machine)', category: 'LEGS', description: 'Machine squat performed on a fixed sled at an angle, back and shoulders braced against pads throughout the movement. Removes the balance and bracing demand of a free squat, allowing heavier, more isolated quad loading.' },
  { name: 'Box Squat', category: 'LEGS', description: 'Barbell back squat performed to a box or bench set at or slightly below parallel, sitting back to briefly touch the box before driving back up. Teaches hip-hinge depth control and removes the stretch-reflex "bounce" out of the bottom, useful for building raw strength out of a dead stop.' },
  { name: 'Cable Kickback', category: 'LEGS', description: 'Standing hip extension using an ankle cable attachment, kicking one leg straight back against resistance while bracing the torso. Isolates the glutes through hip extension, complementing the hip-abduction-focused cable/band work already in the bank.' },
  { name: 'Machine Hip Abductor', category: 'LEGS', description: 'Seated machine exercise pressing the knees outward against resistance pads, isolating the hip abductors and gluteus medius. Same movement pattern as the Cable Hip Abduction above, on fixed equipment instead of a cable — useful when that machine is what\'s available.' },
  { name: 'Machine Hip Adductor', category: 'LEGS', description: 'Seated machine exercise pressing the knees inward against resistance pads, isolating the hip adductors (inner thigh). The adductor counterpart to the Machine Hip Abductor above — first adductor-specific entry in the bank.' },
  { name: 'Walking Lunges', category: 'LEGS', description: 'Alternating forward lunges stepping continuously across a distance rather than returning to the start position each rep, loaded with dumbbells or a barbell. Adds a dynamic-balance and hip-stability demand on top of the standard lunge\'s quad/glute work.' },
  { name: 'Hip Hike (Weighted)', category: 'LEGS', description: "Standing on one leg on a step or box, dropping the opposite hip down and then lifting it back level using only the standing leg's hip abductors, optionally holding extra weight. Isolates the gluteus medius through pelvic control — a common corrective for hip drop during single-leg movements like squats and running." },
  { name: 'Side Plank Leg Lift', category: 'LEGS', description: 'Side plank hold with the top leg lifted straight up against gravity, combining the isometric core demand of a side plank with hip-abductor work in the top leg. Closely related to Side-Lying Hip Abduction above, but performed from a supported plank position instead of lying flat.' },
  { name: 'Single-Leg Hip Thrust', category: 'LEGS', description: 'Hip thrust performed with one foot planted and the other leg extended or held off the ground, upper back supported on a bench. Unilateral, loadable version of the Single-Leg Glute Bridge above — more range and load capacity since the upper back (not the floor) supports the torso.' },
  { name: 'Pistol Squat', category: 'LEGS', description: 'Single-leg bodyweight squat with the non-working leg extended straight out in front, lowering until the working hip is at or below knee height before standing back up. Demanding combination of unilateral strength, ankle/hip mobility, and balance; scale with a box under the hips or a counterbalance held out front.' },
  { name: 'Touch Down Squat', category: 'LEGS', description: 'Single-leg squat reaching the free hand down to lightly touch the floor (or a raised target) at the bottom of the movement before standing back up, the standing leg doing the work throughout. A regressed pistol-squat pattern — the touch point provides balance assistance and a depth target without needing full pistol mobility/strength yet.' },

  // SHOULDERS
  { name: 'Overhead Press', category: 'SHOULDERS', description: 'Standing overhead barbell press targeting the deltoids, triceps, and upper pectorals, with significant core and full-body stabilization demand. Press the bar in a straight vertical path; squeeze glutes and brace the core to avoid lumbar hyperextension.' },
  { name: 'Dumbbell Shoulder Press', category: 'SHOULDERS', description: 'Overhead dumbbell press performed seated or standing, training the deltoids and triceps with independent arm movement. Dumbbells allow a more natural pressing path and expose side-to-side strength imbalances.' },
  { name: 'Lateral Raises', category: 'SHOULDERS', description: 'Dumbbell or cable raise moving the arms out to the sides to approximately shoulder height, isolating the lateral deltoid. Keep a slight bend in the elbows and avoid shrugging; lean slightly forward to improve deltoid targeting.' },
  { name: 'Face Pulls', category: 'SHOULDERS', description: 'Cable exercise pulling a rope attachment toward the face with the elbows high and out, targeting the rear deltoids, external rotators, and mid-traps. A key exercise for shoulder health and postural balance when pressing volume is high.' },
  { name: 'Rear Delt Fly', category: 'SHOULDERS', description: 'Isolation movement for the posterior deltoid and rhomboids, performed with dumbbells (bent-over or incline) or a cable machine. Keep a neutral spine and lead with the elbows to maximize rear delt recruitment over the traps.' },
  { name: 'SA Overhead Lunge', category: 'SHOULDERS', description: 'Walking or stationary lunge performed while holding a single dumbbell or kettlebell locked out overhead in one hand. The lunge is the base; the overhead arm must stay stable and vertical against the offset load throughout. Trains shoulder/scapular stability under unilateral load — valuable for correcting side-to-side overhead stability imbalances.' },
  { name: 'Banded External Rotation', category: 'SHOULDERS', description: 'Standing or half-kneeling external rotation of the shoulder against a light resistance band anchored at elbow height, elbow pinned to the side at 90°. Classic rotator-cuff prehab/rehab movement for shoulder stability and injury prevention; light band tension and full control matter more than resistance.' },
  { name: 'One-Arm Landmine Press', category: 'SHOULDERS', description: 'Single-arm press of a barbell anchored in a landmine attachment, pressing diagonally up and away from the shoulder rather than straight overhead. The angled path is easier on the shoulder joint than a strict overhead press while still training vertical pressing strength unilaterally.' },

  // ARMS
  { name: 'Barbell Bicep Curl', category: 'ARMS', description: 'Standard barbell or dumbbell curl targeting the biceps and brachialis. Keep the elbows fixed at the sides and avoid swinging; a full range of motion including the bottom stretch maximizes hypertrophy stimulus.' },
  { name: 'Dumbbell Bicep Curl', category: 'ARMS', description: 'Unilateral or bilateral dumbbell curl allowing supination through the range of motion to fully engage the biceps. Dumbbells expose left-right strength imbalances and allow a natural wrist rotation compared to a fixed barbell grip.' },
  { name: 'EZ-Bar Curl', category: 'ARMS', description: 'Barbell bicep curl performed with an EZ-curl bar, whose zigzag grip angles the wrists into a semi-supinated position. Reduces wrist and elbow strain compared to a straight barbell curl while still allowing heavier loading than dumbbells — same biceps/brachialis emphasis as the Barbell Bicep Curl.' },
  { name: 'Skull Crusher', category: 'ARMS', description: 'Lying tricep extension with a barbell or EZ-bar, lowering the weight toward the forehead by hinging at the elbows. Targets the long head of the triceps effectively; keep the elbows stable and pointed toward the ceiling throughout.' },
  { name: 'Triceps Pushdown', category: 'ARMS', description: 'Cable pushdown with a bar or rope attachment, isolating the triceps through elbow extension. The rope variant allows the hands to separate at the bottom for a stronger contraction; keep the elbows pinned to the sides.' },
  { name: 'Hammer Curl', category: 'ARMS', description: 'Dumbbell curl performed with a neutral (palms-facing-in) grip throughout, shifting emphasis toward the brachialis and brachioradialis alongside the biceps. The neutral grip is also easier on the wrists than a standard curl for lifters with wrist discomfort.' },

  // CORE
  { name: 'Deadbug', category: 'CORE', description: 'Supine core stability exercise alternately lowering opposite arm and leg while maintaining a flat lower back against the floor. Trains deep anterior core (transverse abdominis) and anti-extension strength; slow and controlled reps are more effective than speed.' },
  { name: 'Pallof Press', category: 'CORE', description: 'Anti-rotation core exercise using a cable or band anchored to the side, pressing the handle away from the chest and resisting rotation. Effective for building lateral core stability and oblique strength; the farther the attachment from the body, the harder the anti-rotation demand.' },
  { name: 'Landmine Rotation', category: 'CORE', description: 'Standing rotational core exercise using a barbell anchored in a landmine attachment (or corner), gripping the free end with both hands and rotating the torso to sweep the bar from hip to hip. Trains rotational core power and anti-rotation control through a full range of motion — the loaded, dynamic counterpart to the Pallof Press\'s static anti-rotation hold.' },
  { name: '90/90 Hip Rotation', category: 'CORE', description: 'Mobility drill in a seated 90/90 position rotating the pelvis and hips to transition between internal and external rotation. Targets hip joint mobility and the deep hip rotators; commonly used in warm-ups or between heavy compound sets.' },
  { name: 'Hip CARs (Controlled Articular Rotations)', category: 'CORE', description: 'Active mobility exercise moving the hip through its full available range of motion in a controlled circle. Used to build and maintain hip mobility and neuromuscular control; typically performed on hands and knees, keeping the spine still.' },
  { name: 'KB Swing', category: 'CORE', description: 'Hip-hinge power exercise with a kettlebell, driving through the glutes and hamstrings to project the bell forward. Trains explosive hip extension, posterior chain strength, and anti-flexion core stability; technique is critical — this is a hinge, not a squat.' },
  { name: 'Farmers Carry', category: 'CORE', description: 'Loaded carry holding a heavy weight in each hand while walking a set distance, training grip, trunk stability, and total-body tension under load. Keep the ribcage stacked over the pelvis and avoid leaning to either side.', trackedFields: ['DISTANCE', 'WEIGHT'] },
  { name: 'Plank', category: 'CORE', description: 'Isometric hold in a forearm or high-plank position, bracing the core to keep a straight line from shoulders to ankles. A foundational anti-extension exercise for core stability; hold duration is the primary progression.', trackedFields: ['DURATION'] },
  { name: 'Cable Crunch', category: 'CORE', description: 'Kneeling cable crunch flexing the spine against resistance from a high pulley, isolating the rectus abdominis through a full range of motion. Curl through the spine rather than just bending at the hips to keep tension on the abs.', link: 'https://youtu.be/dkGwcfo9zto?si=ijMSt0ANPnjCluQ2' },
  { name: 'Hip Flexor Stretch', category: 'CORE', description: 'Held stretch in a half-kneeling position, driving the hips forward to lengthen the hip flexors of the rear leg. Tight hip flexors are a common contributor to hip and lower-back discomfort — hold duration, not reps, is the point.', trackedFields: ['DURATION'] },
  { name: 'Standing Hip Flexor Stretch', category: 'CORE', description: "Standing variant of the hip flexor stretch, shifting the rear leg back and tucking the pelvis under to lengthen the hip flexor without kneeling. Useful as a between-exercise or end-of-session mobility finisher when getting to the floor isn't convenient.", trackedFields: ['DURATION'] },
  { name: 'Sit-Up', category: 'CORE', description: 'Full sit-up from lying to seated, knees bent and feet anchored, hands behind the head or crossed over the chest. Curl up through the spine to a full seated position, then lower back down under control. The standard test-format ab movement, distinct from the machine-based Cable Crunch already in the bank.' },
  { name: 'Toes to Bar', category: 'CORE', description: "Hanging from a bar, raising the legs (straight or slightly bent) until the toes touch the bar, then lowering under control. Dynamic hanging ab movement combining grip endurance with hip flexor and lower-ab strength; regress with knee raises if a full straight-leg toes-to-bar isn't there yet." },
  { name: 'Suitcase Carry', category: 'CORE', description: 'Loaded carry holding a single weight in one hand at the side, like carrying a suitcase, walking a set distance while resisting the pull toward the loaded side. Unilateral counterpart to the Farmers Carry — trains anti-lateral-flexion core strength specifically, since only one side is loaded.', trackedFields: ['DISTANCE', 'WEIGHT'] },

  // CARDIO
  { name: 'Rowing Machine', category: 'CARDIO', description: 'Full-body cardiovascular exercise on an ergometer, engaging the legs, core, and upper body in sequence. Low impact on the joints; excellent for conditioning and active recovery. Drive with the legs first, then lean back and pull the handle to the lower chest.' },
  { name: 'Ski Erg', category: 'CARDIO', description: 'Full-body cardiovascular exercise on a stationary ski ergometer, mimicking the double-poling motion of cross-country skiing by pulling two handles down and back in a rhythmic, standing motion. Engages the lats, triceps, and core heavily alongside the legs; low impact and a strong complement to rowing for varied full-body conditioning.' },
  { name: 'Stationary Bike', category: 'CARDIO', description: 'Low-impact cardiovascular exercise performed on an upright or recumbent stationary bike. Allows sustained aerobic work with minimal joint stress; useful as a warm-up, LISS, or interval training tool.' },
  { name: 'Treadmill', category: 'CARDIO', description: 'Walking or running on a motorized belt at a controlled speed and incline. Versatile for warm-ups, steady-state cardio, or interval sessions; incline walking is a joint-friendly alternative to running for lower-body conditioning.' },
  { name: 'Stepmaster / Stairclimber', category: 'CARDIO', description: 'Cardiovascular machine simulating stair climbing, loading the glutes, quads, and calves while elevating the heart rate. Higher glute recruitment than flat walking; intensity can be adjusted by speed and step height.' },
  { name: 'Cardio (Walk/Bike/Swim)', category: 'CARDIO', description: "Generic low-to-moderate intensity steady-state cardio for general conditioning and active recovery — walking, cycling, or swimming, whichever's convenient. Intensity/pace is a program-specific note, not baked into the exercise itself." },
  { name: 'Burpees', category: 'CARDIO', description: 'Drop to a plank, chest to floor, then explosively return to standing with a jump. Full-body conditioning movement combining a push-up-adjacent pattern with a squat and jump; scale by removing the push-up or the jump.', trackedFields: ['REPS'] },
  { name: 'Burpee Broad Jump', category: 'CARDIO', description: 'Burpee immediately followed by a two-footed broad jump forward instead of a vertical jump, then reset for the next rep from the new position. Adds a horizontal power/distance component on top of the standard burpee\'s conditioning demand.', trackedFields: ['REPS'] },
  { name: 'Burpee Box Jump Over', category: 'CARDIO', description: "Burpee performed facing a box, finishing by jumping up and over it (both feet landing on the far side) instead of a vertical jump in place. Combines the burpee's conditioning demand with the coordination/power of clearing an obstacle.", trackedFields: ['REPS'] },
  { name: 'Wallballs', category: 'CARDIO', description: 'Squat holding a weighted ball at the chest, standing up and throwing it against a target on the wall, catching it on the way down into the next squat. Combines squat volume with a throwing/catching conditioning element; target height and ball weight are both easy to scale.', trackedFields: ['REPS'] },

  // RECOVERY
  { name: 'Mobility & Stretching', category: 'RECOVERY', description: 'General mobility and stretching work — no fixed movement list, just time spent on joint mobility and flexibility. Track total duration only.', trackedFields: ['DURATION'] },

  // OLYMPIC — ⚠️ DO NOT UNCOMMENT until the `OLYMPIC` value exists in the `ExerciseCategory` enum
  // (schema.prisma + migration — not done yet, see docs/exercise-list.md). Uncommenting before
  // that migration runs will fail at the Postgres layer (invalid enum value), not just a TS error.
  // { name: 'Clean and Jerk', category: 'OLYMPIC', description: 'Two-part Olympic lift: a Clean brings the bar from the floor to the shoulders, then a Jerk drives it overhead using a leg-drive dip and re-bend. The full competition lift; highly technical, best coached in person before loading heavy.' },
  // { name: 'Clean', category: 'OLYMPIC', description: 'Olympic lift pulling the bar from the floor to a racked front-squat position on the shoulders in one explosive movement, catching it in a partial or full squat. Trains full-body power and the second-pull triple extension (hips, knees, ankles) shared with the Snatch.' },
  // { name: 'Power Clean', category: 'OLYMPIC', description: "Clean caught in a partial squat (above parallel) rather than a full front squat, demanding more bar speed and less catch-depth mobility. Common training variant when full-squat clean mobility isn't there yet, or to bias more power output per rep." },
  // { name: 'Clean Pull', category: 'OLYMPIC', description: "The pulling portion of the Clean (floor to full extension) performed without the turnover/catch under the bar. Used to overload the pull with more weight than could be caught, or to groove pulling mechanics without the catch's technical demand." },
  // { name: 'Squat Jerk', category: 'OLYMPIC', description: 'Jerk variant where the bar is caught overhead in a full squat rather than a shallow split stance, requiring significant shoulder and hip mobility. Higher mobility demand than a Split Jerk but removes the front-to-back footwork of the split.' },
  // { name: 'Snatch', category: 'OLYMPIC', description: 'Olympic lift pulling the bar from the floor directly overhead in one continuous motion, catching it in a full squat with a wide grip. The most technical barbell lift in the bank — full-body power, mobility, and timing all have to line up in the same rep.' },
  // { name: 'Power Snatch', category: 'OLYMPIC', description: 'Snatch caught in a partial squat (above parallel) rather than a full overhead squat position. Same power-over-mobility trade-off as the Power Clean, applied to the wide-grip pull.' },
  // { name: 'Hang Power Snatch', category: 'OLYMPIC', description: 'Power Snatch starting from a hang position (bar at or above the knee) instead of the floor, removing the first pull. Isolates the second-pull explosive extension and catch, useful for grooving the top half of the lift on its own.' },
  // { name: 'Hang Snatch', category: 'OLYMPIC', description: 'Full-squat Snatch starting from a hang position instead of the floor. Same first-pull removal as the Hang Power Snatch, but caught in a full overhead squat rather than a partial one.' },
  // { name: 'Snatch Balance', category: 'OLYMPIC', description: 'Drill starting with the bar already racked on the back like a squat, dipping and driving it overhead while dropping under it into a full overhead squat catch — no pull involved. Isolates the catch and overhead-squat receiving position in isolation from the pulling portion of the lift.' },
  // { name: 'Overhead Squat', category: 'OLYMPIC', description: "Squat performed with the bar locked out overhead in a wide snatch grip throughout the descent and ascent. Builds the mobility, stability, and core control the Snatch's catch position depends on; also a standalone mobility assessment on its own." },
];

function resolveTrackedFields(exercise: (typeof EXERCISES)[number]): TrackField[] {
  if (exercise.trackedFields) return exercise.trackedFields;
  return exercise.category === 'CARDIO' ? ['DURATION', 'DISTANCE'] : ['REPS', 'WEIGHT'];
}

// ============================================================================
// DO NOT EDIT BELOW THIS LINE
// ============================================================================
async function main() {
  let created = 0;
  let updated = 0;

  for (const exercise of EXERCISES) {
    const existing = await prisma.exercise.findFirst({
      where: { userId: null, name: { equals: exercise.name, mode: 'insensitive' } },
    });

    const data = {
      name: exercise.name,
      category: exercise.category,
      description: exercise.description,
      link: exercise.link,
      trackedFields: resolveTrackedFields(exercise),
    };

    if (existing) {
      await prisma.exercise.update({ where: { id: existing.id }, data });
      updated++;
    } else {
      await prisma.exercise.create({ data: { ...data, userId: null } });
      created++;
    }
  }

  console.log(`Sync complete: ${created} created, ${updated} updated.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
